survos_crawler:
# if you've run symfony proxy:domain:attach my-project, then the error messages will be displayed with this prefix.  That way, you can simply click on a link to open the page.
#    base_url: 'https://my-project.wip/'
    user_class: App\Entity\User
    users:
#        - user@user.com
    max_depth : 3
    routes_to_ignore :
        - 'app_logout'
    paths_to_ignore :
        - '/admin/image/new'
        - '/meiliAdmin/meiliAdmin*'
        - '/workflow/workflow/*'
        - '/compress'
        - '/admin/messenger/schedule'
        - '/inspection/analysis/reflection'
        - '/admin/image/'
        - '/inspection/analysis/formio'
        #recheck
        - 'batch-translate'
        - '/webhook*'
        - '/admin/messenger/transport/async'
        - '/admin/messenger/transport/failed'
        - '/admin/messenger/history*'
        - '/admin/messenger/statistics*'
