<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @generated by code:entity
 */
#[\ORM\Entity(repositoryClass: App\Repository\CiineRepository::class)]
class Ciine
{
	#[\ORM\Id]
	#[\ORM\Column(type: Types::INTEGER)]
    private(set) ?int $id = null;

	#[\ORM\Column(length: 255)]
    private(set) ?string $title = null;

	#[\ORM\Column(length: 255)]
    private(set) ?string $author = null;

	#[\ORM\Column(type: Types::BOOLEAN)]
    private(set) ?bool $featured = null;

	#[\ORM\Column(type: Types::INTEGER)]
    private(set) ?int $duration = null;

	#[\ORM\Column(length: 255)]
    private(set) ?string $durationText = null;

	#[\ORM\Column(type: Types::INTEGER)]
    private(set) ?int $page = null;

	#[\ORM\Column(length: 2048)]
	#[\Assert\Url]
    private(set) ?string $castUrl = null;

	#[\ORM\Column(length: 2048)]
	#[\Assert\Url]
    private(set) ?string $downloadUrl = null;

	#[\ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private(set) ?\DateTimeImmutable $scrapedAt = null;
}
