<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251116103906 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE command_log');
        $this->addSql('ALTER TABLE index_info ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE index_info ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE index_info ADD settings JSONB NOT NULL');
        $this->addSql('ALTER TABLE index_info ALTER locale DROP NOT NULL');
        $this->addSql('ALTER TABLE index_info RENAME COLUMN pixie_code TO primary_key');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE command_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, command_name VARCHAR(255) NOT NULL, arguments JSON DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exit_code INT DEFAULT NULL, error_message TEXT DEFAULT NULL, execution_token VARCHAR(36) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_f4029b64ff89d08b ON command_log (command_name)');
        $this->addSql('CREATE UNIQUE INDEX uniq_f4029b645d4074e ON command_log (execution_token)');
        $this->addSql('CREATE INDEX idx_f4029b64502df587 ON command_log (start_time)');
        $this->addSql('CREATE INDEX idx_f4029b64ff89d08b502df587 ON command_log (command_name, start_time)');
        $this->addSql('ALTER TABLE index_info DROP created_at');
        $this->addSql('ALTER TABLE index_info DROP updated_at');
        $this->addSql('ALTER TABLE index_info DROP settings');
        $this->addSql('ALTER TABLE index_info ALTER locale SET NOT NULL');
        $this->addSql('ALTER TABLE index_info RENAME COLUMN primary_key TO pixie_code');
    }
}
