<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250624222319 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE command_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, command_name VARCHAR(255) NOT NULL, arguments JSON DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exit_code INT DEFAULT NULL, error_message TEXT DEFAULT NULL, execution_token VARCHAR(36) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_F4029B645D4074E ON command_log (execution_token)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F4029B64FF89D08B ON command_log (command_name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F4029B64502DF587 ON command_log (start_time)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F4029B64FF89D08B502DF587 ON command_log (command_name, start_time)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE image (original_url TEXT NOT NULL, code TEXT NOT NULL, resized JSON DEFAULT NULL, original_size INT DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, product_id VARCHAR(255) NOT NULL, PRIMARY KEY(code))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C53D045F4584665A ON image (product_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE product (sku VARCHAR(255) NOT NULL, data JSONB DEFAULT NULL, name VARCHAR(255) NOT NULL, rating INT NOT NULL, stock INT NOT NULL, PRIMARY KEY(sku))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE image ADD CONSTRAINT FK_C53D045F4584665A FOREIGN KEY (product_id) REFERENCES product (sku) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE image DROP CONSTRAINT FK_C53D045F4584665A
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE command_log
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE image
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE product
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE messenger_messages
        SQL);
    }
}
